apiVersion: v1
kind: Service
metadata:
  name: prismic-svc
  labels:
    run: prismic
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    run: prismic
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prismic-ing
spec:
  rules:
    - host: <PROXY-HOST>
      http:
        paths:
          - path: /
            backend:
              serviceName: prismic-svc
              servicePort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: prismic-deploy
  labels:
    run: prismic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: prismic
    spec:
      containers:
      - name: prismic
        image: escaletech/buran:0.1
        ports:
        - containerPort: 3000
        env:
          - name: BACKEND_URL
            value: 'http://<PRISMIC-REPO-NAME>.cdn.prismic.io'
          - name: CACHE_PROVIDER
            value: memory
